// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DirController from "./dir_controller"
application.register("dir", DirController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EventController from "./event_controller"
application.register("event", EventController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
