# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "spec/**/*"
  - "config/**/*"
  - "db/**/*"
  - "bin/**/*"
  - "vendor/**/*"
  - "tmp/**/*"
  - "node_modules/**/*"
  - "public/**/*"
  - "log/**/*"
  - "storage/**/*"
